In [5]:
import numpy as np

numpy_array = np.array([2,4,8,2,4,5])
numpy_array

array([2, 4, 8, 2, 4, 5])

To Create a multidimensiona Array we can use a list of lists

In [7]:
import numpy as np

numpy_2d_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
numpy_2d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

We can also Check the details of this array,Like what type of data it is carrying etc.
Like array.dtype will give the data type of the array.


In [9]:
import numpy as np

array = np.array([1,2,3])
array.dtype

dtype('int64')

We can also Check the shape of the array using array.shape

In [11]:
numpy_2d_array.shape

(3, 3)

To chek the size or total number of variable we use array_name.size

In [12]:
numpy_2d_array.size

9

To check the dimension we use array.ndim

In [13]:
numpy_2d_array.ndim

2

To Create a Two dimensional Array with all entries 0s or 1s
thE ZEROS want first argument as a shape so we add (2,3) with a outer bracket
This will create a array of float type
So we mention the dtype as int as second parameter 

In [14]:
zeros = np.zeros((2,3),dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

Arange - Intialises the Value from 0-n n exclusive 

In [16]:
arr_r =np.arange(10)
arr_r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Suppose if want 10 float values between 1-5
For that case we use inbuilt function linespace
Inclusive of 1 and 5

In [ ]:
arr_linespace = np.linspace(1,5,10)
arr_linespace

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

There is also a function called Logspace if we want exponentiallty Growth