NumPy slicing allows you to extract portions of arrays using a concise syntax.

- Use the colon (`:`) operator to specify `start`, `stop`, and `step` indices:  
    `array[start:stop:step]`
- Slicing works for both one-dimensional and multi-dimensional arrays.
- For multi-dimensional arrays, slice along each axis using commas:  
    `array[row_start:row_stop, col_start:col_stop]`
- Slicing returns a view of the original array, not a copy.  
    Changes to the slice affect the original array.

In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr[:1]

array([[1, 2, 3]])

In [ ]:
arr[0:1,2:3]

array([[3]])

To Get The values Stored at 1,3 means not continuous values

In [10]:
arr[0:2,0:3:2]

array([[1, 3],
       [4, 6]])