# NumPy Indexing

NumPy indexing allows you to access and manipulate elements of arrays efficiently. Here are the main types of indexing in NumPy:

## 1. Basic Indexing

- Single element access  
- Slicing

## 2. Integer Array Indexing

- Select elements at specific positions using lists or arrays of indices

## 3. Boolean Indexing

- Use boolean arrays to select elements

## 4. Fancy Indexing

- Allows selection of arbitrary items using integer arrays

## 5. Ellipsis (`...`)

- Used to select remaining unspecified dimensions

## Summary Table

| Type                | Example                | Description                      |
|---------------------|-----------------------|----------------------------------|
| Basic               |                       | Single element                   |
| Slicing             |                       | Range of elements                |
| Integer Array       |                       | Specific elements                |
| Boolean             |                       | Condition-based selection        |
| Fancy               |                       | Arbitrary rows/columns           |
| Ellipsis            |                       | All dimensions, first column     |

NumPy indexing is powerful for data selection, manipulation, and analysis.


In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr[0]

array([1, 2, 3])

In [15]:
arr[0][1]


np.int64(2)

In [17]:
arr[0,1]

np.int64(2)

In [18]:
arr[-1,-1]

np.int64(6)

In [20]:
arr[1,2]=55
arr

array([[ 1,  2,  3],
       [ 4,  5, 55]])

In [21]:
arr[1]=7
arr

array([[1, 2, 3],
       [7, 7, 7]])

In [22]:
arr[1]+2
arr

array([[1, 2, 3],
       [7, 7, 7]])