In [1]:
import numpy as np


In [4]:
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([2,3,4])
print(arr2)

[1 2 3]
[2 3 4]


In [6]:
arr1 + arr2

array([3, 5, 7])

In [7]:
arr1 + 5

array([6, 7, 8])

In [10]:
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([[2],[4],[6]])
print(arr2)

[1 2 3]
[[2]
 [4]
 [6]]


In [11]:
arr1 + arr2

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

# Rules for Broadcasting
- The dimension of array should Match
- If Dimension Dont match then numpy will try to broadcast
- Then the dimension of either row or coklumn should be one  